default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: corsicafacile_dev

test:
  <<: *default
  database: corsicafacile_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: require

